#py-calc: package.yml
matches:
  - regex: \((?P<argz>.*?)\)=
    replace: "{{output}}"
    vars:
      - name: output
        type: script
        params:
          args: [python3, -c, 'print({{argz}})']
